# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformExporter < Formula
  desc "Export artifacts to terraform files"
  homepage ""
  version "1.2.0"
  license "MIT"

  depends_on "nodejs" => :optional
  depends_on "openjdk@17" => :optional
  depends_on "python3" => :optional

  on_macos do
    url "https://github.com/gideaworx/terraform-exporter/releases/download/v1.2.0/terraform-exporter_darwin_all.zip"
    sha256 "51da2c1fcc6eaedbbf08b8a4dfb53d717e0333443b9d50d20926d1fe637eebd7"

    def install
      bin.install "terraform-exporter"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gideaworx/terraform-exporter/releases/download/v1.2.0/terraform-exporter_linux_arm64.zip"
      sha256 "9307337398fd523343674fca8b4eb0d776fa0b7279599ab73ca022e861fabaa6"

      def install
        bin.install "terraform-exporter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gideaworx/terraform-exporter/releases/download/v1.2.0/terraform-exporter_linux_amd64.zip"
      sha256 "f69e7c8cc05fe661af960e5fa7082052709737d4666214a9b62ce592d602fee5"

      def install
        bin.install "terraform-exporter"
      end
    end
  end

  test do
    system "#{bin}/terraform-exporter", "--version"
  end
end
