# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformExporterAT012 < Formula
  desc "Export artifacts to terraform files"
  homepage "https://github.com/gideaworx/terraform-exporter"
  version "0.1.2"
  license "MIT"

  depends_on "nodejs" => :optional
  depends_on "python3" => :optional
  depends_on "openjdk@17" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gideaworx/terraform-exporter/releases/download/v0.1.2/terraform-exporter_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a5dba4d8877572def8413549738449c1a60f667a008ba41cfd85337134df24d7"

      def install
        bin.install "terraform-exporter"
        prefix.install "LICENSE"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gideaworx/terraform-exporter/releases/download/v0.1.2/terraform-exporter_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "06efa73e23e964ef87ecf819b1f871cc6f6c3e3b663ae8b3e9573728c874a3da"

      def install
        bin.install "terraform-exporter"
        prefix.install "LICENSE"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gideaworx/terraform-exporter/releases/download/v0.1.2/terraform-exporter_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "323b8dd61b6a8d0982ba0b2946614702cae7b752fe073d73555dc2c6724174af"

      def install
        bin.install "terraform-exporter"
        prefix.install "LICENSE"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gideaworx/terraform-exporter/releases/download/v0.1.2/terraform-exporter_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "49a13ce77251cc9478bc39fc37bef9e47e6c72c1a3cb7e952186d903aa741325"

      def install
        bin.install "terraform-exporter"
        prefix.install "LICENSE"
      end
    end
  end

  test do
    system "#{bin}/terraform-exporter --version"
  end
end
