# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformExporter < Formula
  desc "Export artifacts to terraform files"
  homepage "https://github.com/gideaworx/terraform-exporter"
  version "1.0.0"
  license "MIT"

  depends_on "nodejs" => :optional
  depends_on "openjdk@17" => :optional
  depends_on "python3" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gideaworx/terraform-exporter/releases/download/v1.0.0/terraform-exporter_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ccdd8efb10dfdafd50cc3dfeecae523067030ab3c50a62d8602c528d3a1f3154"

      def install
        bin.install "terraform-exporter"
        prefix.install "LICENSE"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gideaworx/terraform-exporter/releases/download/v1.0.0/terraform-exporter_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "6f0c7a3708a49095856992c4558e6370fce595427f589f92415f647e3e29a293"

      def install
        bin.install "terraform-exporter"
        prefix.install "LICENSE"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gideaworx/terraform-exporter/releases/download/v1.0.0/terraform-exporter_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c5fd2273f4689406863a503b7d70ea04aa3bd5d7731b7b113a8bb5e04eccee53"

      def install
        bin.install "terraform-exporter"
        prefix.install "LICENSE"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gideaworx/terraform-exporter/releases/download/v1.0.0/terraform-exporter_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "d0a662be33c0c004bf819f9dec2eff84bb54797e45d3973acc5da42fa11324cd"

      def install
        bin.install "terraform-exporter"
        prefix.install "LICENSE"
      end
    end
  end

  test do
    system "#{bin}/terraform-exporter", "--version"
  end
end
